---
title: "Data"
execute:
  echo: false
  warning: false
  error: false
---

```{r "imports"}
library(tidyverse)
library(gt)
library(plotly)
library(slider)
library(systemfonts)
library(fontawesome)

# Path to your local font file
font_path <- "static/cardenio_modern_font/CardenioModern-Regular.otf"

# Register the font with systemfonts
register_font(name = "CardenioModern", plain = font_path)

invisible(
  lapply(
    list.files(
      "./R",
      full.names = TRUE
    ),
    source
  )
)
```

```{r "Download Google Sheet"}
wingspan_scores <- get_google_sheet(
  sheetId = 2096833443
) %>%
  mutate(
    timestamp = if_else(
      !is.na(
        mdy(
          .$timestamp
        )
      ),
      .$timestamp |>
        mdy() |>
        as.character(),
      .$timestamp |>
        as.character()
    )
  ) |>
  arrange(
    timestamp
  )
  
wingspan_scores <- wingspan_scores |>
    mutate(
        game = 1:nrow(
            wingspan_scores
        ),
        .before = 1
    )

flock_mode_scores <- wingspan_scores |>
    filter(
        n_players >= 6
    )

wingspan_scores <- wingspan_scores |>
    filter(
        n_players < 6
    )
```

```{r "Stacked player score"}
stacked_player_scores <- lapply(
  1:7,
  iterative_pivot,
  df = wingspan_scores
) |>
  bind_rows() |>
  drop_na() |>
  group_by(game) |>
  mutate(
    winner = case_when(
      score >= max(score, na.rm = TRUE) ~ TRUE,
      .default = FALSE
    )
  ) |>
  ungroup()
```

```{r "Table: Summary"}

stacked_player_scores |>
  filter(
    score_type == "total_score"
  ) |>
  group_by(
    Name
  ) |>
  mutate(
    group_size = n()
  ) |>
  filter(
    group_size >= 10
  ) |>
  arrange(
    game
  ) |>
  mutate(
    "N" = n(),
    "Won" = sum(winner),
    "%" = round(
      100 *
        sum(
          winner
        ) /
        n(),
      1
    ),
    "Max" = max(score),
    "Min" = min(score),
    "Mean" = round(
      mean(score),
      1
    )
  ) |>
  select(
    c(
      Name,
      "N",
      "Won",
      "%",
      "Max",
      "Min",
      "Mean"
    )
  ) |>
  filter(
    row_number() == 1
  ) |>
  mutate(
    Name = str_trunc(
      Name,
      width = 7
    )
  ) |>
  arrange(
    Name
  ) |>
  gt(
    groupname_col = NULL,
    rowname_col = "Name"
  ) |>
  tab_header(
    title = "Summary statistics",
    subtitle = "Min. 10 games played"
  ) |>
  tab_options(
    table.background.color = "#4C5766",
    table.font.size = px(16),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table_body.hlines.color = "transparent",
    table_body.border.bottom.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    column_labels.border.top.color = "transparent"
  ) |>
  opt_css(
    css = "
    table tr:hover {
      background-color: var(--brand-blue-grey);
    }
    "
  )

```

```{r "Plot: Total score per game"}

player_scores_total <- stacked_player_scores |>
  filter(
    score_type == "total_score"
  ) |>
  group_by(
    Name
  ) |>
  mutate(
    group_size = n()
  ) |>
  filter(
    group_size >= 10
  ) |>
  arrange(
    game
  ) |>
  mutate(
    game_number = row_number()
  ) %>%
  split(
    .,
    .$Name
  )

p <- player_scores_total[[1]] %>%
  plot_ly(
    x = ~game_number,
    y = ~score,
    type = "scatter",
    mode = "lines",
    visible = TRUE
  )

for (name in names(player_scores_total)[-1]) {
  if (name != "Alex") {
    p <- p %>%
      add_lines(
        data = player_scores_total[[name]],
        x = ~game_number,
        y = ~score,
        visible = FALSE,
        name = name
      )
  }
}

pp <- p %>%
  layout(
    title = list(
      text = "Total score per game",
      x = 0,
      xanchor = "left"
    ),
    xaxis = list(title = "Game number"),
    yaxis = list(title = "Score"),
    showlegend = FALSE,
    margin = list(
      l = 40,
      r = 0
    ),
    updatemenus = list(
      list(
        y = 1.15,
        yanchor = "top",
        x = 0.99,
        xanchor = "right",
        buttons = lapply(
          names(player_scores_total),
          function(name) {
            list(
              method = "update",
              args = list(
                list(
                  visible = as.logical(
                    match(
                      names(
                        player_scores_total
                      ),
                      name,
                      nomatch = FALSE
                    )
                  )
                )
              ),
              label = name
            )
          }
        )
      )
    )
  ) |>
  config(
    modeBarButtonsToRemove = list(
      "zoom2d",
      "pan2d",
      "toImage",
      "zoomIn2d",
      "zoomOut2d",
      "autoScale2d",
      "hoverCompareCartesian",
      "hoverClosestCartesian"
    ),
    displayModeBar = FALSE
  )

pp
```

```{r "Plot: Rolling win rate"}

player_scores_total <- stacked_player_scores |>
  filter(
    score_type == "total_score"
  ) |>
  group_by(
    Name
  ) |>
  mutate(
    group_size = n()
  ) |>
  filter(
    group_size >= 10
  ) |>
  arrange(
    game
  ) |>
  mutate(
    game_number = row_number(),
    rolling_wr = 100 *
      slide_dbl(
        winner,
        mean,
        .before = 50,
        .after = 0
      )
  ) %>%
  split(
    .,
    .$Name
  )

p <- player_scores_total[[1]] %>%
  plot_ly(
    x = ~game_number,
    y = ~rolling_wr,
    type = "scatter",
    mode = "lines",
    visible = TRUE
  )

for (name in names(player_scores_total)[-1]) {
  if (name != "Alex") {
    p <- p %>%
      add_lines(
        data = player_scores_total[[name]],
        x = ~game_number,
        y = ~rolling_wr,
        visible = FALSE,
        name = name
      )
  }
}

pp <- p %>%
  layout(
    title = list(
      text = "Rolling % (50 games)",
      x = 0,
      xanchor = "left"
    ),
    xaxis = list(title = "Game number"),
    yaxis = list(title = "Win rate (%)"),
    showlegend = FALSE,
    margin = list(
      l = 40,
      r = 0
    ),
    updatemenus = list(
      list(
        y = 1.15,
        yanchor = "top",
        x = 0.99,
        xanchor = "right",
        buttons = lapply(
          names(player_scores_total),
          function(name) {
            list(
              method = "update",
              args = list(
                list(
                  visible = as.logical(
                    match(
                      names(
                        player_scores_total
                      ),
                      name,
                      nomatch = FALSE
                    )
                  )
                )
              ),
              label = name
            )
          }
        )
      )
    )
  ) |>
  config(
    modeBarButtonsToRemove = list(
      "zoom2d",
      "pan2d",
      "toImage",
      "zoomIn2d",
      "zoomOut2d",
      "autoScale2d",
      "hoverCompareCartesian",
      "hoverClosestCartesian"
    ),
    displayModeBar = FALSE
  )

pp
```