---
title: "Records & Leaderboard"
execute:
  echo: false
  warning: false
  error: false
---

```{r "imports"}
library(tidyverse)
library(gt)
library(plotly)
library(slider)
library(systemfonts)
library(fontawesome)

# Path to your local font file
font_path <- "static/cardenio_modern_font/CardenioModern-Regular.otf"

# Register the font with systemfonts
register_font(name = "CardenioModern", plain = font_path)

invisible(
  lapply(
    list.files(
      "./R",
      full.names = TRUE
    ),
    source
  )
)
```

```{r "Download Google Sheet"}
wingspan_scores <- get_google_sheet(
  sheetId = 2096833443
) %>%
  mutate(
    timestamp = if_else(
      !is.na(
        mdy(
          .$timestamp
        )
      ),
      .$timestamp |>
        mdy() |>
        as.character(),
      .$timestamp |>
        as.character()
    )
  ) |>
  arrange(
    timestamp
  )
  
wingspan_scores <- wingspan_scores |>
    mutate(
        game = 1:nrow(
            wingspan_scores
        ),
        .before = 1
    )

flock_mode_scores <- wingspan_scores |>
    filter(
        n_players >= 6
    )

wingspan_scores <- wingspan_scores |>
    filter(
        n_players < 6
    )
```

```{r "Stacked player score"}
stacked_player_scores <- lapply(
  1:7,
  iterative_pivot,
  df = wingspan_scores
) |>
  bind_rows() |>
  drop_na() |>
  group_by(game) |>
  mutate(
    winner = case_when(
      score >= max(score, na.rm = TRUE) ~ TRUE,
      .default = FALSE
    )
  ) |>
  ungroup()
```

```{r "Compute leaderboard records"}

leader_board_table <- data.frame(
  Record = character(),
  Holder = character(),
  Value = integer(),
  Date = character()
)

# Highest score per type
highest_scores_per_type <- stacked_player_scores |>
  group_by(
    score_type
  ) |>
  arrange(
    game
  ) |>
  select(
    c(
      game,
      timestamp,
      Name,
      score,
      score_type
    )
  ) %>%
  mutate(
    cumulative_max = cummax(
      score
    ),
    is_new_max = cumulative_max !=
      lag(
        cumulative_max,
        default = first(
          cumulative_max
        )
      ),
    corresponding_Name = ifelse(
      is_new_max | row_number() == 1,
      Name,
      NA
    ),
    corresponding_timestamp = ifelse(
      is_new_max | row_number() == 1,
      timestamp,
      NA
    ),
    score_type = recode(
      score_type,
      birds = "Most Bird Points",
      bonus_cards = "Most Bonus Card Points",
      "end-of-round_goals" = "Most End-of-round Points",
      eggs = "Most Eggs Laid",
      food_on_cards = "Most Cached Food",
      tucked_cards = "Most Tucked Cards",
      nectar = "Most Nectar Points",
      duet_tokens = "Most Duet Tokens",
      hummingbird_track = "Hummingbird Track",
      total_score = "Highest Score"
    )
  ) %>%
  fill(
    corresponding_Name,
    .direction = "down"
  ) %>%
  fill(
    corresponding_timestamp,
    .direction = "down"
  ) |>
  group_by(
    score_type
  ) |>
  filter(
    score > 0,
    (is_new_max == 1) | (score == cumulative_max)
  ) |>
  slice_max(
    order_by = score,
    n = 3
  ) |>
  ungroup() |>
  group_by(
    score_type,
    score,
    Name
  ) |>
  slice_min(
    order_by = timestamp,
    n = 1
  ) |>
  ungroup() |>
  arrange(
    factor(
      score_type,
      levels = c(
        "Highest Score",
        "Most Bird Points",
        "Most Bonus Card Points",
        "Most End-of-round Points",
        "Most Eggs Laid",
        "Most Cached Food",
        "Most Tucked Cards",
        "Most Nectar Points",
        "Most Duet Tokens",
        "Highest Hummingbird Track"
      )
    ),
    desc(score)
  ) %>%
  select(
    c(
      score_type,
      Name,
      score,
      timestamp
    )
  )

# Records
records <- highest_scores_per_type |>
  rename(
    c(
      "Record" = score_type,
      "Name" = Name,
      "Value" = score,
      "Date" = timestamp
    )
  ) |>
  mutate(
    Date = format(
      as.Date(
        Date
      ),
      format = "%m/%d/%Y"
    ) |>
    mdy()
  ) |>
  group_by(Record) |>
  arrange(
    factor(
      Record,
      levels = c(
        "Highest Score",
        "Most Bird Points",
        "Most Bonus Card Points",
        "Most End-of-round Points",
        "Most Eggs Laid",
        "Most Cached Food",
        "Most Tucked Cards",
        "Most Nectar Points",
        "Most Duet Tokens",
        "Highest Hummingbird Track"
      )
    ),
    desc(Value),
    Date
  ) |>
  mutate(
    icon = case_when(
      row_number() <= 3 ~ "trophy",
      .default = NA
    ),
    fill_colour = case_when(
      row_number() == 1 ~ "gold",
      row_number() == 2 ~ "silver",
      row_number() == 3 ~ "#CD7F32",
      .default = NA
    ),
    .before = Name
  ) |>
  mutate(
    Date = format(
      as.Date(
        Date
      ),
      format = "%m/%d/%Y"
    )
  )
```
```{r "Generate leaderboard aggregate table"}
unique_names_ge_10 <- stacked_player_scores |>
  filter(
    score_type == "total_score"
  ) |>
  group_by(
    Name
  ) |>
  summarise(
    group_size = n()
  ) |>
  filter(
    group_size >= 10
  ) |>
  pull(Name)

expand_grid(
  Name = unique_names_ge_10,
  fill_colour = c(
    "gold",
    "silver",
    "#CD7F32"
  )
) |>
  left_join(
    records |>
      group_by(
        Name,
        fill_colour
      ) |>
      summarise(
        count = n()
      )
  ) |>
  mutate(
    count = replace_na(
      count,
      0
    )
  ) |>
  pivot_wider(
    names_from = fill_colour,
    values_from = count
  ) |>
  mutate(
    Total = gold + silver + `#CD7F32`
  ) |>
  gt() |>
  tab_header(
    title = "Records"
  ) |>
  cols_label(
    # Wrap the fa() output in html() so gt processes it as HTML
    gold = html(
      fa(
        "trophy",
        fill = "gold"
      )
    ),
    silver = html(
      fa(
        "trophy",
        fill = "silver"
      )
    ),
    `#CD7F32` = html(
      fa(
        "trophy",
        fill = "#CD7F32"
      )
    )
  ) |>
  tab_options(
    table.background.color = "#4C5766",
    table.font.size = px(16)
  ) |>
  opt_css(
    css = "
    table tr:hover {
      background-color: var(--brand-blue-grey);
    }
    "
  )
```

```{r "Generate leaderboard detailed table"}
records |>
  gt(
    groupname_col = "Record",
    row_group_as_column = TRUE
  ) |>
  tab_header(
    title = "Leaderboard"
  ) |>
  fmt_icon(
    icon,
    height = "1em",
    fill_color = from_column(
      "fill_colour"
    )
  ) |>
  cols_hide(
    columns = fill_colour
  ) |>
  cols_align(
    c(
      icon,
      Date
    ),
    align = "center"
  ) |>
  tab_options(
    table.background.color = "#4C5766",
    table.font.size = px(16)
  ) |>
  opt_css(
    css = "
    table tr:hover {
      background-color: var(--brand-blue-grey);
    }
    "
  ) |>
  sub_missing(
    columns = everything(), # Target all columns
    missing_text = "" # Replace NA with "---"
  ) |>
  cols_label(
    icon = ""
  )
```


```{r "Make leaderboard plot"}

# Highest score per type
historical_scores_per_type <- stacked_player_scores |>
  group_by(
    score_type
  ) |>
  arrange(
    game
  ) |>
  select(
    c(
      game,
      timestamp,
      Name,
      score,
      score_type
    )
  ) %>%
  mutate(
    cumulative_max = cummax(
      score
    ),
    is_new_max = cumulative_max !=
      lag(
        cumulative_max,
        default = first(
          cumulative_max
        )
      ),
    corresponding_Name = ifelse(
      is_new_max | row_number() == 1,
      Name,
      NA
    ),
    corresponding_timestamp = ifelse(
      is_new_max | row_number() == 1,
      timestamp,
      NA
    ),
    corresponding_game = ifelse(
      is_new_max | row_number() == 1,
      game,
      NA
    ),
    score_type = recode(
      score_type,
      birds = "Most Bird Points",
      bonus_cards = "Most Bonus Card Points",
      duet_tokens = "Most Duet Tokens",
      eggs = "Most Eggs Laid",
      "end-of-round_goals" = "Most End-of-round Points",
      food_on_cards = "Most Cached Food",
      nectar = "Most Nectar Points",
      total_score = "Highest Score",
      tucked_cards = "Most Tucked Cards"
    )
  ) |>
  fill(
    c(corresponding_Name, corresponding_timestamp, corresponding_game),
    .direction = "down"
  )

historical_scores_per_type |>
  filter(score_type == "Highest Score") |>
  ggplot() +
  geom_point(aes(x = game, y = cumulative_max, colour = corresponding_Name)) +
  theme_minimal()

```